# Generated by Django 5.2.8 on 2025-12-17 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_reset_otp_user_reset_otp_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_verifier',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('administrator', 'Administrator'), ('wholesaler', 'Wholesaler'), ('distributor', 'Distributor'), ('customer', 'Customer')], max_length=20, null=True),
        ),
    ]
