# Generated by Django 5.2.8 on 2025-12-23 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_ticket_admin_response_ticket_assigned_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('administrator', 'Administrator'), ('wholesaler', 'Wholesaler'), ('retailer', 'Retailer'), ('hospital', 'Hospital'), ('pharmacy', 'Pharmacy'), ('customer', 'Customer')], max_length=20, null=True),
        ),
    ]
