# Generated by Django 5.2.8 on 2025-12-23 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('administrator', 'Administrator'), ('wholesaler', 'Wholesaler'), ('retailer', 'Retailer'), ('hospital', 'Hospital'), ('pharmacy', 'Pharmacy'), ('end_user', 'End User')], max_length=20, null=True),
        ),
    ]
