# Generated by Django 5.2.8 on 2026-04-10

from django.db import migrations, models
import django.db.models.deletion
import string
import secrets


def _generate_unique_code(apps, prefix):
    User = apps.get_model('users', 'User')
    alphabet = string.ascii_uppercase + string.digits
    while True:
        candidate = f"{prefix}{''.join(secrets.choice(alphabet) for _ in range(8))}"
        if not User.objects.filter(unique_code=candidate).exists() and not User.objects.filter(referral_code=candidate).exists():
            return candidate


def backfill_user_codes(apps, schema_editor):
    User = apps.get_model('users', 'User')
    for user in User.objects.all().iterator():
        update_fields = []
        if not user.unique_code:
            user.unique_code = _generate_unique_code(apps, 'USR')
            update_fields.append('unique_code')
        if not user.referral_code:
            user.referral_code = _generate_unique_code(apps, 'REF')
            update_fields.append('referral_code')
        if update_fields:
            user.save(update_fields=update_fields)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='referred_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_users', to='users.user'),
        ),
        migrations.AddField(
            model_name='user',
            name='referral_code',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='reward_points',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='unique_code',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
        migrations.RunPython(backfill_user_codes, migrations.RunPython.noop),
    ]
