# Generated by Django 5.2.8 on 2026-05-13 23:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_user_unique_code_user_referral_and_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='kyc_rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='kyc_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='kyc_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='kyc_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='kyc_verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kyc_verified_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('administrator', 'Administrator'), ('wholesaler', 'Wholesaler'), ('retailer', 'Retailer'), ('hospital', 'Hospital'), ('pharmacy', 'Pharmacy'), ('end_user', 'End User'), ('online_vendor', 'Online Vendor')], max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='KYCSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_type', models.CharField(choices=[('wholesaler', 'Wholesaler'), ('retailer', 'Retailer'), ('pharmacy', 'Pharmacy'), ('hospital', 'Hospital'), ('online_vendor', 'Online Vendor')], max_length=20)),
                ('business_name', models.CharField(max_length=255)),
                ('contact_number', models.CharField(max_length=20)),
                ('business_address', models.TextField()),
                ('cac_document', models.FileField(blank=True, null=True, upload_to='kyc_documents/%Y/%m/%d/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_submission', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kyc_verified_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'KYC Submission',
                'verbose_name_plural': 'KYC Submissions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'user'], name='users_kycsu_status_e6f4d9_idx'), models.Index(fields=['-created_at'], name='users_kycsu_created_cfd666_idx')],
            },
        ),
    ]
