# Generated by Django 5.2.8 on 2026-05-21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_user_kyc_rejection_reason_user_kyc_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KYCSubmissionAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('status_changed', 'Status Changed'), ('email', 'Email Event')], max_length=20)),
                ('from_status', models.CharField(blank=True, max_length=20, null=True)),
                ('to_status', models.CharField(blank=True, max_length=20, null=True)),
                ('email_status', models.CharField(blank=True, choices=[('', 'N/A'), ('queued', 'Queued'), ('sent', 'Sent'), ('failed', 'Failed')], default='', max_length=20)),
                ('message', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kyc_audit_events', to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='users.kycsubmission')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='kycsubmissionauditlog',
            index=models.Index(fields=['submission', '-created_at'], name='users_kycsu_submiss_5eef1f_idx'),
        ),
        migrations.AddIndex(
            model_name='kycsubmissionauditlog',
            index=models.Index(fields=['event_type', 'created_at'], name='users_kycsu_event_t_3a1218_idx'),
        ),
    ]
