# Generated by Django 5.2.8 on 2026-05-25 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_kycsubmissionauditlog'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='kycsubmissionauditlog',
            new_name='users_kycsu_submiss_9b5ef0_idx',
            old_name='users_kycsu_submiss_5eef1f_idx',
        ),
        migrations.RenameIndex(
            model_name='kycsubmissionauditlog',
            new_name='users_kycsu_event_t_29564b_idx',
            old_name='users_kycsu_event_t_3a1218_idx',
        ),
    ]
