# Generated by Django 5.2.8 on 2025-12-23 10:27

from django.db import migrations
from django.db.models import F, Q
from django.db.models.functions import Greatest


def backfill_inventory_deduction(apps, schema_editor):
    """Deduct inventory for orders that have been paid or shipped/delivered"""
    Order = apps.get_model('ecom', 'Order')
    OrderItem = apps.get_model('ecom', 'OrderItem')
    Product = apps.get_model('admin_dashboard', 'Product')
    
    # Find all orders that should have inventory deducted
    orders_to_process = Order.objects.filter(
        inventory_deducted=False
    ).filter(
        Q(payment_status='completed') | 
        Q(status__in=['shipped', 'delivered'])
    )
    
    for order in orders_to_process:
        items = order.items.select_related('product')
        for item in items:
            if item.product_id:
                # Deduct inventory, ensuring it doesn't go below 0
                Product.objects.filter(id=item.product_id).update(
                    stock=Greatest(F('stock') - item.quantity, 0)
                )
        # Mark order as inventory_deducted
        order.inventory_deducted = True
        order.save(update_fields=['inventory_deducted'])


def reverse_inventory_deduction(apps, schema_editor):
    """Reverse the inventory deductions (if needed)"""
    Order = apps.get_model('ecom', 'Order')
    OrderItem = apps.get_model('ecom', 'OrderItem')
    Product = apps.get_model('admin_dashboard', 'Product')
    
    # Find all orders that were marked as deducted
    orders_to_reverse = Order.objects.filter(
        inventory_deducted=True
    ).filter(
        Q(payment_status='completed') | 
        Q(status__in=['shipped', 'delivered'])
    )
    
    for order in orders_to_reverse:
        items = order.items.select_related('product')
        for item in items:
            if item.product_id:
                # Add inventory back
                Product.objects.filter(id=item.product_id).update(
                    stock=F('stock') + item.quantity
                )
        # Mark order as not deducted
        order.inventory_deducted = False
        order.save(update_fields=['inventory_deducted'])


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0003_order_inventory_deducted'),
    ]

    operations = [
        migrations.RunPython(backfill_inventory_deduction, reverse_inventory_deduction),
    ]
