# Generated by Django 5.2.8 on 2026-04-10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_user_unique_code_user_referral_and_points'),
        ('ecom', '0005_order_shipping_fee_order_speedaf_order_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RewardPointConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_per_purchase', models.PositiveIntegerField(default=1)),
                ('referral_bonus_points', models.PositiveIntegerField(default=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reward_configs_updated', to='users.user')),
            ],
            options={
                'verbose_name': 'Reward Point Configuration',
                'verbose_name_plural': 'Reward Point Configuration',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='purchase_points_awarded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='referral_code_used',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='referral_points_awarded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='referrer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_orders', to='users.user'),
        ),
    ]
