# Generated by Django 5.2.8 on 2026-04-10 22:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0006_reward_point_config_and_referrals'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RewardPointLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField()),
                ('reason', models.CharField(choices=[('purchase', 'Purchase Reward'), ('referral', 'Referral Bonus')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='ecom.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_ledger', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reward Point Entry',
                'verbose_name_plural': 'Reward Point Ledger',
                'ordering': ['-created_at'],
            },
        ),
    ]
