# Generated by Django 5.2.8 on 2026-04-20 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0007_reward_point_ledger'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='gateway_reference',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_provider',
            field=models.CharField(choices=[('paystack', 'Paystack'), ('monnify', 'Monnify')], default='paystack', max_length=20),
        ),
    ]
