# Generated by Django 5.2.8 on 2026-05-25 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0011_rewardpointconfig_minimum_withdrawal_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='checkout_idempotency_key',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='walletwithdrawalrequest',
            name='idempotency_key',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
