# Generated by Django 5.2.8 on 2026-05-25 16:32

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0012_order_checkout_idempotency_key_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='checkout_code',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='checkout_code_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkout_code_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='checkout_code_points_awarded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='checkout_discount_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='order',
            name='checkout_discount_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='checkout_code_points',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rewardpointconfig',
            name='checkout_code_discount_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Percentage discount applied to the product subtotal when a valid checkout code is used.', max_digits=5),
        ),
        migrations.AlterField(
            model_name='rewardpointledger',
            name='reason',
            field=models.CharField(choices=[('purchase', 'Purchase Reward'), ('referral', 'Referral Bonus'), ('checkout_code', 'Checkout Code Reward'), ('conversion_debit', 'Converted to Wallet')], max_length=20),
        ),
    ]
