# Generated by Django 5.2.8 on 2025-12-17 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0005_product_sku_alter_product_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_best_seller',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
