# Generated by Django 5.2.8 on 2025-12-20 07:24

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0006_product_is_best_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_female',
            field=models.BooleanField(default=False, help_text='Product for female'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_general',
            field=models.BooleanField(default=True, help_text='Product for everyone'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_male',
            field=models.BooleanField(default=False, help_text='Product for male'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Description'),
        ),
    ]
