# Generated by Django 5.2.8 on 2025-12-20 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0008_blogcategory_blogpost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogcategory',
            name='parent',
        ),
        migrations.AlterField(
            model_name='blogcategory',
            name='name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
