# Generated by Django 5.2.8 on 2026-04-27 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0010_product_customer_price_product_hospital_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='weight_kg',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='Product unit weight in kg', max_digits=8),
        ),
    ]
