# Generated by Django 5.2.8 on 2026-05-15 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0012_dailywebsitevisit'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='online_vendor_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
