# Generated by Django 5.2.8 on 2026-05-25 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0013_add_online_vendor_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='checkout_code_points',
            field=models.PositiveIntegerField(default=0, help_text='Points awarded to the owner of a checkout unique code when this product is purchased with that code.'),
        ),
    ]
