# Generated by Django 5.2.8 on 2026-05-25 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0014_product_checkout_code_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='checkout_code_discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Discount percentage applied to this product when a valid checkout code is used.', max_digits=5),
        ),
    ]
