from django.urls import path
from .views import (
    signup,
    verify_otp,
    resend_otp,
    login,
    logout,
    dashboard,
    reward_dashboard,
    profile,
    change_password,
    password_reset_request,
    password_reset_verify,
    password_reset_new,
    create_ticket,
    view_tickets,
    ticket_detail,
    order_history,
    order_history_more,
    rewards_load_more,
    convert_rewards_to_wallet,
    add_wallet_bank_account,
    request_wallet_withdrawal,
    wallet_bank_list,
    wallet_account_lookup,
    partner_signup,
    submit_kyc,
    kyc_status,
)

urlpatterns = [
    path('signup/', signup, name='signup'),
    path('partner-signup/', partner_signup, name='partner-signup'),
    path('verify-otp/', verify_otp, name='verify-otp'),
    path('resend-otp/', resend_otp, name='resend-otp'),
    path('login/', login, name='login'),
    path('logout/', logout, name='logout'),
    path('dashboard/', dashboard, name='user-dashboard'),
    path('dashboard/', dashboard, name='dashboard'),
    path('reward/', reward_dashboard, name='reward-dashboard'),
    path('reward/convert/', convert_rewards_to_wallet, name='reward-convert'),
    path('reward/bank-account/add/', add_wallet_bank_account, name='reward-bank-account-add'),
    path('reward/banks/', wallet_bank_list, name='reward-banks'),
    path('reward/account-lookup/', wallet_account_lookup, name='reward-account-lookup'),
    path('reward/withdraw/', request_wallet_withdrawal, name='reward-withdraw'),
    path('profile/', profile, name='profile'),
    path('change-password/', change_password, name='change-password'),
    path('password-reset/', password_reset_request, name='password-reset-request'),
    path('password-reset/verify/', password_reset_verify, name='password-reset-verify'),
    path('password-reset/new/', password_reset_new, name='password-reset-new'),
    path('create-ticket/', create_ticket, name='create-ticket'),
    path('tickets/', view_tickets, name='view-tickets'),
    path('tickets/<uuid:ticket_id>/', ticket_detail, name='ticket-detail'),
    path('order-history/', order_history, name='order-history'),
    path('order-history/more/', order_history_more, name='order-history-more'),
    path('rewards/more/', rewards_load_more, name='rewards-load-more'),
    path('submit-kyc/', submit_kyc, name='submit-kyc'),
    path('kyc-status/', kyc_status, name='kyc-status'),
]
